runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:APP
service: product-updater

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: ...
  KEY: ...

runtime_config:
  python_version: 3


manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
